/**
 * Generate a Tailwind CSS sources file from the app config.
 *
 * Creates a CSS file with @source directives for all tool packages,
 * so Tailwind v4 scans their source files for utility class usage.
 *
 * Can be used two ways:
 *
 * 1. **As a build step** — generate the file before running Vite:
 * ```ts
 * import { writeTailwindSources } from '@ydtb/anvil-toolkit/build'
 * await writeTailwindSources(config, './client/styles/tool-sources.css')
 * ```
 *
 * 2. **As a Vite plugin** — auto-generates on dev server start:
 * ```ts
 * import { tailwindSourcesPlugin } from '@ydtb/anvil-toolkit/build'
 * // Add to vite.config.ts plugins
 * ```
 *
 * Then in your app's CSS:
 * ```css
 * @import './tool-sources.css';
 * @import 'tailwindcss';
 * ```
 */

import type { AppConfig } from '@ydtb/anvil'
import { collectTools } from './collect-tools.ts'

/**
 * Generate CSS content with @source directives for all tool packages.
 *
 * Resolves package names to filesystem paths relative to the output file.
 * Tailwind v4's @source does not resolve node package names inside
 * @import'ed CSS files — only filesystem paths work reliably.
 *
 * @param config - AppConfig from compose.config.ts
 * @param outputDir - Directory where the CSS file will be written (used to compute relative paths)
 */
export function generateTailwindSources(config: AppConfig, outputDir?: string): string {
  const tools = collectTools(config)
  const lines: string[] = [
    '/* Auto-generated by @ydtb/anvil-toolkit */',
    '/* Do not edit — regenerated on each build */',
    '',
  ]

  for (const tool of tools) {
    const resolved = resolvePackagePath(tool.package, outputDir)
    lines.push(`@source "${resolved}/src/**/*.{ts,tsx,js,jsx}";`)
  }

  return lines.join('\n') + '\n'
}

/**
 * Resolve a package name to a filesystem path relative to the output directory.
 *
 * Tries multiple strategies because the Vite plugin context may not have
 * `require.resolve` available (ESM) or it may resolve to a .bun cache
 * path instead of the workspace source.
 *
 * Strategy 1: Walk node_modules for the package directory (works with symlinks/workspaces)
 * Strategy 2: require.resolve the main export and walk up to package.json
 * Fallback: return package name as-is
 */
function resolvePackagePath(packageName: string, outputDir?: string): string {
  const path = require('path')
  const fs = require('fs')

  // Strategy 1: Walk node_modules from cwd (handles bun workspaces + symlinks)
  try {
    const nmPath = path.join(process.cwd(), 'node_modules', ...packageName.split('/'))
    const resolved = fs.realpathSync(nmPath)
    if (fs.existsSync(path.join(resolved, 'package.json'))) {
      return outputDir ? path.relative(outputDir, resolved) : resolved
    }
  } catch {
    // node_modules lookup failed — try next strategy
  }

  // Strategy 2: require.resolve and walk up
  try {
    let dir = path.dirname(require.resolve(packageName))
    while (dir !== '/' && !fs.existsSync(path.join(dir, 'package.json'))) {
      dir = path.dirname(dir)
    }
    if (dir !== '/') {
      return outputDir ? path.relative(outputDir, dir) : dir
    }
  } catch {
    // require.resolve failed — fall through
  }

  console.warn(`[anvil-toolkit] Could not resolve filesystem path for ${packageName}, using package name as-is`)
  return packageName
}

/**
 * Write the Tailwind sources CSS file to disk.
 *
 * @param config - AppConfig from compose.config.ts
 * @param outputPath - Where to write the file (e.g., './client/styles/tool-sources.css')
 */
export async function writeTailwindSources(config: AppConfig, outputPath: string): Promise<void> {
  const fs = await import('fs')
  const path = await import('path')
  const outputDir = path.resolve(path.dirname(outputPath))
  const content = generateTailwindSources(config, outputDir)

  const dir = path.dirname(outputPath)
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true })
  }

  // Only write if content changed (avoid triggering unnecessary rebuilds)
  const existing = fs.existsSync(outputPath) ? fs.readFileSync(outputPath, 'utf-8') : ''
  if (existing !== content) {
    fs.writeFileSync(outputPath, content)
    const toolCount = collectTools(config).length
    console.log(`[anvil-toolkit] Generated Tailwind sources: ${outputPath} (${toolCount} tools)`)
  }
}

/**
 * Vite plugin that auto-generates the Tailwind sources CSS file
 * on dev server start and when config changes.
 *
 * @param config - AppConfig from compose.config.ts
 * @param outputPath - Where to write the file (default: './tailwind-sources.css')
 */
export function tailwindSourcesPlugin(config: AppConfig, outputPath = './tailwind-sources.css') {
  return {
    name: 'anvil:tailwind-sources',

    async buildStart() {
      await writeTailwindSources(config, outputPath)
    },
  }
}
