/**
 * Generate a Tailwind CSS sources file from the app config.
 *
 * Creates a CSS file with @source directives for all tool packages,
 * so Tailwind v4 scans their source files for utility class usage.
 *
 * Can be used two ways:
 *
 * 1. **As a build step** — generate the file before running Vite:
 * ```ts
 * import { writeTailwindSources } from '@ydtb/anvil-toolkit/build'
 * await writeTailwindSources(config, './client/styles/tool-sources.css')
 * ```
 *
 * 2. **As a Vite plugin** — auto-generates on dev server start:
 * ```ts
 * import { tailwindSourcesPlugin } from '@ydtb/anvil-toolkit/build'
 * // Add to vite.config.ts plugins
 * ```
 *
 * Then in your app's CSS:
 * ```css
 * @import './tool-sources.css';
 * @import 'tailwindcss';
 * ```
 */

import type { AppConfig } from '@ydtb/anvil'
import { collectTools } from './collect-tools.ts'

/**
 * Generate CSS content with @source directives for all tool packages.
 *
 * Resolves package names to filesystem paths relative to the output file.
 * Tailwind v4's @source does not resolve node package names inside
 * @import'ed CSS files — only filesystem paths work reliably.
 *
 * @param config - AppConfig from compose.config.ts
 * @param outputDir - Directory where the CSS file will be written (used to compute relative paths)
 */
export function generateTailwindSources(config: AppConfig, outputDir?: string): string {
  const tools = collectTools(config)
  const lines: string[] = [
    '/* Auto-generated by @ydtb/anvil-toolkit */',
    '/* Do not edit — regenerated on each build */',
    '',
  ]

  for (const tool of tools) {
    const resolved = resolvePackagePath(tool.package, outputDir)
    lines.push(`@source "${resolved}/src/**/*.{ts,tsx,js,jsx}";`)
  }

  return lines.join('\n') + '\n'
}

/**
 * Resolve a package name to a filesystem path relative to the output directory.
 * Falls back to the package name if resolution fails (e.g., in tests).
 */
function resolvePackagePath(packageName: string, outputDir?: string): string {
  try {
    const path = require('path')
    // Try to resolve the package's directory via require.resolve or import.meta.resolve
    const resolved = require.resolve(`${packageName}/package.json`)
    const packageDir = path.dirname(resolved)
    if (outputDir) {
      return path.relative(outputDir, packageDir)
    }
    return packageDir
  } catch {
    // Fallback: return package name as-is (works if Tailwind can resolve it)
    return packageName
  }
}

/**
 * Write the Tailwind sources CSS file to disk.
 *
 * @param config - AppConfig from compose.config.ts
 * @param outputPath - Where to write the file (e.g., './client/styles/tool-sources.css')
 */
export async function writeTailwindSources(config: AppConfig, outputPath: string): Promise<void> {
  const fs = await import('fs')
  const path = await import('path')
  const outputDir = path.resolve(path.dirname(outputPath))
  const content = generateTailwindSources(config, outputDir)

  const dir = path.dirname(outputPath)
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true })
  }

  // Only write if content changed (avoid triggering unnecessary rebuilds)
  const existing = fs.existsSync(outputPath) ? fs.readFileSync(outputPath, 'utf-8') : ''
  if (existing !== content) {
    fs.writeFileSync(outputPath, content)
    const toolCount = collectTools(config).length
    console.log(`[anvil-toolkit] Generated Tailwind sources: ${outputPath} (${toolCount} tools)`)
  }
}

/**
 * Vite plugin that auto-generates the Tailwind sources CSS file
 * on dev server start and when config changes.
 *
 * @param config - AppConfig from compose.config.ts
 * @param outputPath - Where to write the file (default: './tailwind-sources.css')
 */
export function tailwindSourcesPlugin(config: AppConfig, outputPath = './tailwind-sources.css') {
  return {
    name: 'anvil:tailwind-sources',

    async buildStart() {
      await writeTailwindSources(config, outputPath)
    },
  }
}
