/**
 * Generate a Tailwind CSS sources file from the app config.
 *
 * Creates a CSS file with @source directives for all tool packages,
 * so Tailwind v4 scans their source files for utility class usage.
 *
 * Can be used two ways:
 *
 * 1. **As a build step** — generate the file before running Vite:
 * ```ts
 * import { writeTailwindSources } from '@ydtb/anvil-toolkit/build'
 * await writeTailwindSources(config, './client/styles/tool-sources.css')
 * ```
 *
 * 2. **As a Vite plugin** — auto-generates on dev server start:
 * ```ts
 * import { tailwindSourcesPlugin } from '@ydtb/anvil-toolkit/build'
 * // Add to vite.config.ts plugins
 * ```
 *
 * Then in your app's CSS:
 * ```css
 * @import './tool-sources.css';
 * @import 'tailwindcss';
 * ```
 */

import type { AppConfig } from '@ydtb/anvil'
import { collectTools } from './collect-tools.ts'

/**
 * Generate CSS content with @source directives for all tool packages.
 */
export function generateTailwindSources(config: AppConfig): string {
  const tools = collectTools(config)
  const lines: string[] = [
    '/* Auto-generated by @ydtb/anvil-toolkit */',
    '/* Do not edit — regenerated on each build */',
    '',
  ]

  for (const tool of tools) {
    lines.push(`@source "${tool.package}/src/**/*.{ts,tsx,js,jsx}";`)
  }

  return lines.join('\n') + '\n'
}

/**
 * Write the Tailwind sources CSS file to disk.
 *
 * @param config - AppConfig from compose.config.ts
 * @param outputPath - Where to write the file (e.g., './client/styles/tool-sources.css')
 */
export async function writeTailwindSources(config: AppConfig, outputPath: string): Promise<void> {
  const content = generateTailwindSources(config)
  const fs = await import('fs')
  const path = await import('path')

  const dir = path.dirname(outputPath)
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true })
  }

  // Only write if content changed (avoid triggering unnecessary rebuilds)
  const existing = fs.existsSync(outputPath) ? fs.readFileSync(outputPath, 'utf-8') : ''
  if (existing !== content) {
    fs.writeFileSync(outputPath, content)
    console.log(`[anvil-toolkit] Generated Tailwind sources: ${outputPath} (${tools(config).length} tools)`)
  }
}

function tools(config: AppConfig) {
  return collectTools(config)
}

/**
 * Vite plugin that auto-generates the Tailwind sources CSS file
 * on dev server start and when config changes.
 *
 * @param config - AppConfig from compose.config.ts
 * @param outputPath - Where to write the file (default: './tailwind-sources.css')
 */
export function tailwindSourcesPlugin(config: AppConfig, outputPath = './tailwind-sources.css') {
  return {
    name: 'anvil:tailwind-sources',

    async buildStart() {
      await writeTailwindSources(config, outputPath)
    },
  }
}
